version: '3.4'

services:
  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: "no"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basketdb:
    image: redis:alpine
    container_name: basketdb
    restart: "no"
    ports:
      - "6379:6379"

  discountdb:
    image: postgres
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=DiscountDb
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: orderdb
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    restart: "no"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: "no"
    ports:
      - "5672:5672"
      - "15672:15672" # id/pw: guest/guest

  mongoclient:
    image: mongoclient/mongoclient
    container_name: mongoclient
    ports:
      - "3000:3000"
    depends_on:
      - catalogdb

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: "unless-stopped"
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@shockz.io
      - PGADMIN_DEFAULT_PASSWORD=P@ssw0rd
    restart: "no"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  elasticsearch:
    image: elasticsearch:7.17.2 # not support latest tag
    container_name: elasticsearch
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    # check url: localhost:9200, localhost:9200/_aliases, localhost:9200/products/_bulk, localhost:9200/products/_search

  kibana:
    image: kibana:7.17.2 # not support latest tag
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:
  mssql_data:
  elasticsearch-data:
